AplicacaoMVCLinq/Models/Cliente.cs
namespace AplicacaoMVCLinq.Models
{
    public class Cliente
    {

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public DateOnly DataNasc { get; set; }

        public Cliente(int id, string nome, string email, string telefone, DateOnly dataNasc)
        {
            this.Id = id;
            this.Nome = nome;
            this.Email = email;
            this.Telefone = telefone;
            this.DataNasc = dataNasc;
        }
    }
}

AplicacaoMVCLinq/Models/ErrorViewModel.cs
namespace AplicacaoMVCLinq.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicacaoMVCLinq/Controllers/ClienteController.cs
using AplicacaoMVCLinq.Models;
using Microsoft.AspNetCore.Mvc;
using static AplicacaoMVCLinq.Models.Cliente;

namespace AplicacaoMVCLinq.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetClientes()
        {
            Cliente C1 = new Cliente(1, "Alice", "alice@gmail.com", "1234-5678 ", new DateOnly(2000, 6, 1));
            Cliente C2 = new Cliente(2, "Claudio", "Claudio@gmail.com", "2234-5678 ", new DateOnly(1999, 7, 21));
            Cliente C3 = new Cliente(3, "Laécio", "Laécio@gmail.com", "3234-5678 ", new DateOnly(2001, 7, 8));
            Cliente C4 = new Cliente(4, "Camila", "cami@gmail.com", "4234-5678 ", new DateOnly(1999, 7, 30));
            Cliente C5 = new Cliente(5, "Roberto", "roberto@gmail.com", "5234-5678 ", new DateOnly(1999, 5, 26));

            List<Cliente> Cliente = new List<Cliente>();
            Cliente.Add(C1);
            Cliente.Add(C2);
            Cliente.Add(C3);
            Cliente.Add(C4);
            Cliente.Add(C5);

            return View(Cliente);
        }
    }
}

AplicacaoMVCLinq/Controllers/HomeController.cs
using AplicacaoMVCLinq.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AplicacaoMVCLinq.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicacaoMVCLinq/Views/Cliente/GetClientes.cshtml
@model IEnumerable<AplicacaoMVCLinq.Models.Cliente>
<h1>Lista de Clientes</h1>
@{
    ViewData["Title"] = "Listar Clientes";
}
<div class="container table-responsive">

    <table class="table table-dark table-striped table-hover">
        <thead>

            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Data de Nascimento</th>

        <tbody>
                    @foreach (var cliente in Model)
                    {
                <tr>

                    <td>@cliente.Id </td>
                    <td>@cliente.Nome </td>
                    <td>@cliente.Email  </td>
                    <td>@cliente.Telefone </td>
                    <td>@cliente.DataNasc </td>
                </tr>

                    }
        </tbody>



        </tr>
        </thead>
    </table>
</div>

AplicacaoMVCLinq/Views/Cliente/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>bootstrap 5.3</h1>
<p class="text-sm-end text-primary bg-black">Esse texto será alinha a direita em tela pequena (sm) até qualquer tamanho </p>
<p class="text-md-center text-success bg-success ">Esse texto será alinha a direita em tela média (md) até qualquer tamanho </p>
<p class="text-lg-end text-danger bg-warning">Esse texto será alinha a direita em tela grande (lg) até qualquer tamanho </p>

AplicacaoMVCLinq/Views/Home/Index.cshtml
<div class="row bg-success m-0"><div class="col bg-danger">header</div></div>

<div class="row m-0 gap-3 g-3">
    <div class="col-12 col-md-3 bg-primary" style="height: 200px">DIV 1</div>
    <div class="col-12 col-md bg-info" style="height: 200px">DIV 2</div>
    <div class="col-12 d-md-none d-lg-block col-lg-2 bg-warning" style="height: 200px">DIV 3</div>
</div>
<div class="row m-0 gap-3 g-3">
    <div class="col bg-black"> FOOTER-1</div>
    <div class="col bg-success"> FOOTER-2</div>
    <div class="col bg-primary">FOOTER 3</div>
</div>

AplicacaoMVCLinq/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacaoMVCLinq</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacaoMVCLinq.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicacaoMVCLinq</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="GetClientes">Lista de clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Lista de clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AplicacaoMVCLinq - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>